[env:esp32dev]
platform  = espressif32
board     = esp32dev
framework = arduino

upload_speed  = 115200
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time

build_flags =
    -DCORE_DEBUG_LEVEL=3

board_upload.flash_mode = dio
board_upload.f_flash     = 40000000

lib_deps =
    https://github.com/adafruit/Adafruit_SSD1306.git
    https://github.com/adafruit/Adafruit-GFX-Library.git
    https://github.com/adafruit/Adafruit_BusIO.git
    https://github.com/adafruit/DHT-sensor-library.git
    https://github.com/madhephaestus/ESP32Servo.git
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    https://github.com/me-no-dev/AsyncTCP.git
    https://github.com/bblanchon/ArduinoJson.git
